"""
Seed data: investment instrument universe (demo dataset).

Realistic Indian-market-style instruments across 8 asset categories. All figures are
illustrative / historical demo data and are labelled as such in the UI.
"""

INVESTMENTS = [
    # ---- Equity ----
    {"name": "Bluechip Equity Fund", "category": "Equity", "risk_level": 4, "expected_return": 12.5, "volatility": 16.0, "liquidity": 4, "minimum_investment": 5000, "horizon_min_years": 5, "horizon_max_years": 25, "suitable_profiles": ["Moderately Aggressive", "Aggressive"], "goal_suitability": ["Wealth Creation", "Retirement", "Higher Education"], "historical_performance": [{"year": 2021, "return": 24.1}, {"year": 2022, "return": -3.4}, {"year": 2023, "return": 18.7}, {"year": 2024, "return": 14.2}, {"year": 2025, "return": 11.8}], "description": "Diversified large-cap equity exposure aimed at long-term capital appreciation."},
    {"name": "Small & Mid Cap Growth", "category": "Equity", "risk_level": 5, "expected_return": 14.5, "volatility": 22.0, "liquidity": 3, "minimum_investment": 5000, "horizon_min_years": 7, "horizon_max_years": 25, "suitable_profiles": ["Aggressive"], "goal_suitability": ["Wealth Creation", "Retirement"], "historical_performance": [{"year": 2021, "return": 38.2}, {"year": 2022, "return": -9.1}, {"year": 2023, "return": 31.4}, {"year": 2024, "return": 20.6}, {"year": 2025, "return": 9.3}], "description": "High-growth potential from emerging companies with elevated volatility."},
    {"name": "Dividend Yield Equity", "category": "Equity", "risk_level": 3, "expected_return": 10.8, "volatility": 12.5, "liquidity": 4, "minimum_investment": 5000, "horizon_min_years": 4, "horizon_max_years": 20, "suitable_profiles": ["Moderate", "Moderately Aggressive"], "goal_suitability": ["Wealth Creation", "Retirement"], "historical_performance": [{"year": 2021, "return": 19.0}, {"year": 2022, "return": 2.1}, {"year": 2023, "return": 14.5}, {"year": 2024, "return": 12.0}, {"year": 2025, "return": 10.4}], "description": "Equities with steady dividend income and moderate growth."},

    # ---- Mutual Funds ----
    {"name": "Balanced Advantage Fund", "category": "Mutual Funds", "risk_level": 3, "expected_return": 10.2, "volatility": 9.5, "liquidity": 4, "minimum_investment": 1000, "horizon_min_years": 3, "horizon_max_years": 15, "suitable_profiles": ["Moderate", "Moderately Conservative", "Moderately Aggressive"], "goal_suitability": ["Wealth Creation", "House Purchase", "Retirement", "Higher Education"], "historical_performance": [{"year": 2021, "return": 15.2}, {"year": 2022, "return": 3.8}, {"year": 2023, "return": 12.1}, {"year": 2024, "return": 10.5}, {"year": 2025, "return": 9.2}], "description": "Dynamically balances equity and debt to manage risk across cycles."},
    {"name": "Multi-Asset Allocation Fund", "category": "Mutual Funds", "risk_level": 3, "expected_return": 9.6, "volatility": 8.5, "liquidity": 4, "minimum_investment": 1000, "horizon_min_years": 3, "horizon_max_years": 12, "suitable_profiles": ["Moderate", "Moderately Conservative"], "goal_suitability": ["Wealth Creation", "House Purchase", "Marriage"], "historical_performance": [{"year": 2021, "return": 14.0}, {"year": 2022, "return": 4.5}, {"year": 2023, "return": 11.3}, {"year": 2024, "return": 9.8}, {"year": 2025, "return": 8.6}], "description": "Blends equity, debt and gold for diversified, all-weather returns."},
    {"name": "ELSS Tax Saver Fund", "category": "Mutual Funds", "risk_level": 4, "expected_return": 12.0, "volatility": 15.0, "liquidity": 2, "minimum_investment": 500, "horizon_min_years": 3, "horizon_max_years": 20, "suitable_profiles": ["Moderate", "Moderately Aggressive", "Aggressive"], "goal_suitability": ["Wealth Creation", "Retirement"], "historical_performance": [{"year": 2021, "return": 22.0}, {"year": 2022, "return": -1.2}, {"year": 2023, "return": 17.0}, {"year": 2024, "return": 13.5}, {"year": 2025, "return": 10.9}], "description": "Equity fund with tax benefits under Sec 80C and a 3-year lock-in."},

    # ---- ETFs ----
    {"name": "Nifty 50 Index ETF", "category": "ETFs", "risk_level": 4, "expected_return": 11.5, "volatility": 15.5, "liquidity": 5, "minimum_investment": 500, "horizon_min_years": 5, "horizon_max_years": 25, "suitable_profiles": ["Moderate", "Moderately Aggressive", "Aggressive"], "goal_suitability": ["Wealth Creation", "Retirement"], "historical_performance": [{"year": 2021, "return": 21.3}, {"year": 2022, "return": 4.0}, {"year": 2023, "return": 15.8}, {"year": 2024, "return": 12.9}, {"year": 2025, "return": 10.2}], "description": "Low-cost passive exposure to India's top 50 companies."},
    {"name": "Nasdaq 100 ETF", "category": "ETFs", "risk_level": 5, "expected_return": 13.5, "volatility": 20.0, "liquidity": 5, "minimum_investment": 1000, "horizon_min_years": 6, "horizon_max_years": 25, "suitable_profiles": ["Aggressive", "Moderately Aggressive"], "goal_suitability": ["Wealth Creation", "Retirement"], "historical_performance": [{"year": 2021, "return": 27.5}, {"year": 2022, "return": -18.0}, {"year": 2023, "return": 43.4}, {"year": 2024, "return": 24.9}, {"year": 2025, "return": 8.1}], "description": "Global technology exposure for diversification beyond domestic markets."},

    # ---- Bonds ----
    {"name": "Corporate Bond Fund", "category": "Bonds", "risk_level": 2, "expected_return": 7.4, "volatility": 4.0, "liquidity": 3, "minimum_investment": 1000, "horizon_min_years": 2, "horizon_max_years": 8, "suitable_profiles": ["Moderately Conservative", "Moderate", "Conservative"], "goal_suitability": ["House Purchase", "Marriage", "Vehicle Purchase", "Emergency Fund"], "historical_performance": [{"year": 2021, "return": 6.8}, {"year": 2022, "return": 5.2}, {"year": 2023, "return": 7.1}, {"year": 2024, "return": 7.6}, {"year": 2025, "return": 7.4}], "description": "High-quality corporate debt offering stable, predictable income."},
    {"name": "Dynamic Bond Fund", "category": "Bonds", "risk_level": 2, "expected_return": 7.8, "volatility": 5.0, "liquidity": 3, "minimum_investment": 1000, "horizon_min_years": 3, "horizon_max_years": 10, "suitable_profiles": ["Moderately Conservative", "Moderate"], "goal_suitability": ["Retirement", "House Purchase"], "historical_performance": [{"year": 2021, "return": 6.5}, {"year": 2022, "return": 4.8}, {"year": 2023, "return": 7.9}, {"year": 2024, "return": 8.2}, {"year": 2025, "return": 7.5}], "description": "Actively managed duration to adapt to interest-rate cycles."},

    # ---- Fixed Deposits ----
    {"name": "Bank Fixed Deposit", "category": "Fixed Deposits", "risk_level": 1, "expected_return": 6.8, "volatility": 0.5, "liquidity": 2, "minimum_investment": 1000, "horizon_min_years": 1, "horizon_max_years": 5, "suitable_profiles": ["Conservative", "Moderately Conservative"], "goal_suitability": ["Emergency Fund", "Vehicle Purchase", "Marriage"], "historical_performance": [{"year": 2021, "return": 5.5}, {"year": 2022, "return": 6.0}, {"year": 2023, "return": 6.9}, {"year": 2024, "return": 7.0}, {"year": 2025, "return": 6.8}], "description": "Capital-protected deposit with fixed, guaranteed interest."},
    {"name": "Corporate FD (AAA)", "category": "Fixed Deposits", "risk_level": 2, "expected_return": 7.9, "volatility": 1.0, "liquidity": 2, "minimum_investment": 10000, "horizon_min_years": 1, "horizon_max_years": 5, "suitable_profiles": ["Moderately Conservative", "Conservative"], "goal_suitability": ["Emergency Fund", "Vehicle Purchase"], "historical_performance": [{"year": 2021, "return": 7.2}, {"year": 2022, "return": 7.5}, {"year": 2023, "return": 8.0}, {"year": 2024, "return": 8.1}, {"year": 2025, "return": 7.9}], "description": "Higher-yield fixed deposit from top-rated corporates."},

    # ---- Gold ----
    {"name": "Sovereign Gold Bond", "category": "Gold", "risk_level": 2, "expected_return": 8.5, "volatility": 12.0, "liquidity": 2, "minimum_investment": 5000, "horizon_min_years": 5, "horizon_max_years": 8, "suitable_profiles": ["Moderate", "Moderately Conservative", "Conservative"], "goal_suitability": ["Wealth Creation", "Marriage", "Retirement"], "historical_performance": [{"year": 2021, "return": -4.2}, {"year": 2022, "return": 13.9}, {"year": 2023, "return": 15.1}, {"year": 2024, "return": 20.5}, {"year": 2025, "return": 11.0}], "description": "Government-backed gold with 2.5% annual interest plus price gains."},
    {"name": "Gold ETF", "category": "Gold", "risk_level": 3, "expected_return": 8.0, "volatility": 13.0, "liquidity": 5, "minimum_investment": 500, "horizon_min_years": 3, "horizon_max_years": 15, "suitable_profiles": ["Moderate", "Moderately Aggressive"], "goal_suitability": ["Wealth Creation", "Marriage"], "historical_performance": [{"year": 2021, "return": -3.8}, {"year": 2022, "return": 12.5}, {"year": 2023, "return": 14.0}, {"year": 2024, "return": 19.8}, {"year": 2025, "return": 10.2}], "description": "Liquid gold exposure as an inflation and portfolio hedge."},

    # ---- Government Securities ----
    {"name": "Govt Securities Fund (G-Sec)", "category": "Government Securities", "risk_level": 1, "expected_return": 7.0, "volatility": 3.5, "liquidity": 3, "minimum_investment": 1000, "horizon_min_years": 3, "horizon_max_years": 12, "suitable_profiles": ["Conservative", "Moderately Conservative"], "goal_suitability": ["Retirement", "Emergency Fund", "House Purchase"], "historical_performance": [{"year": 2021, "return": 3.2}, {"year": 2022, "return": 2.8}, {"year": 2023, "return": 7.5}, {"year": 2024, "return": 8.0}, {"year": 2025, "return": 7.1}], "description": "Sovereign-backed debt with minimal credit risk."},
    {"name": "PPF (Public Provident Fund)", "category": "Government Securities", "risk_level": 1, "expected_return": 7.1, "volatility": 0.2, "liquidity": 1, "minimum_investment": 500, "horizon_min_years": 15, "horizon_max_years": 15, "suitable_profiles": ["Conservative", "Moderately Conservative"], "goal_suitability": ["Retirement", "Higher Education"], "historical_performance": [{"year": 2021, "return": 7.1}, {"year": 2022, "return": 7.1}, {"year": 2023, "return": 7.1}, {"year": 2024, "return": 7.1}, {"year": 2025, "return": 7.1}], "description": "Tax-free, government-guaranteed long-term savings with a 15-year term."},

    # ---- REITs ----
    {"name": "Commercial REIT", "category": "REITs", "risk_level": 3, "expected_return": 9.0, "volatility": 11.0, "liquidity": 4, "minimum_investment": 10000, "horizon_min_years": 4, "horizon_max_years": 15, "suitable_profiles": ["Moderate", "Moderately Aggressive"], "goal_suitability": ["Wealth Creation", "Retirement"], "historical_performance": [{"year": 2021, "return": 11.2}, {"year": 2022, "return": 6.0}, {"year": 2023, "return": 8.5}, {"year": 2024, "return": 9.8}, {"year": 2025, "return": 9.1}], "description": "Income from commercial real estate with regular distributions."},
]

MARKET_INDICES = [
    {"name": "Nifty 50", "value": 24850.5, "change_pct": 0.82, "trend": [23100, 23400, 23900, 24200, 24100, 24600, 24850]},
    {"name": "Sensex", "value": 81620.0, "change_pct": 0.74, "trend": [76200, 77100, 78500, 79800, 79200, 80900, 81620]},
    {"name": "Nifty Bank", "value": 52140.3, "change_pct": -0.31, "trend": [50100, 50800, 51600, 52300, 51900, 52400, 52140]},
    {"name": "Gold (10g)", "value": 74250.0, "change_pct": 0.45, "trend": [68000, 69500, 70800, 72100, 73000, 73800, 74250]},
]
